### ISSUE TITLE
composer.json requires redis extension even if we dont need it

### ISSUE THREAD

**Issue by neilime** [ekreative/health-check-bundle#29]
Hi,

This bundle force to have the "redis" extension installed (https://github.com/ekreative/health-check-bundle/blob/513e9d87135f0c930c332d47b6f302b00c6e70bf/composer.json#L22), but it is too bad for project which are not using redis.

I propose to set it as suggested dependency: https://getcomposer.org/doc/04-schema.md#suggest

Thanks

**Comment by mcfedr** [comment]
That would probably fine as a PR

**Comment by neilime** [comment]
Here it is https://github.com/ekreative/health-check-bundle/pull/30

**Comment by mcfedr** [comment]
Released as 1.13.0
